'''
    ..........
    ...#......
    ..........
    ....a.....
    ..........
    .....a....
    ..........
    ......#...
    ..........
    ..........

    - Antinodes occur at any point that is perfectly in 
      line with two antennas of the same frequency.

      They only occur on the outer bounds of a pair of 
      antennas; and the distance between each antenna
      dictates the distance of the antinodes.

    ..........
    ...#......
    #.........
    ....a.....
    ........a.
    .....a....
    ..#.......
    ......#...
    ..........
    ..........

    - Antinodes cannot appear out of bounds.

    ..........
    ...#......
    #.........
    ....a.....
    ........a.
    .....a....
    ..#.......
    ......A...
    ..........
    ..........

    - Antinodes with different frequencies do not create
      antinodes. However, they can obstruct any location
      that does contain an antinode. (These are still counted)

'''

def main():
    pass


if __name__ == '__main__':
    main()